### ISSUE TITLE
Objective-c

### ISSUE THREAD

**Issue by geogerar** [appzzman/iBeacon#7]
Which is the name of your previous library in objective-c?
Is there any graphical presentation in objective-c like the radar you have in swift?

Any way.... thank you ...waiting an answer!

George Gerardis

**Comment by gulfcoastdev** [comment]
George,
Check the https://github.com/izotx/JMCBeaconManager/tree/Objective-C
It doesn't have the radar and It's not actively maintained. 

The files you need are:
JMCBeaconManager.h
JMCBeaconManager.m
